# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 126dbbd4e3db6f8bf1bfe47a580b3dd65cb7e9383e489f1834fd6a93dc1cdecd5a0bce8aadbb43cfeec58da552f0a7a3211ccb09c4be928e73ef3a569eaacb5a

test:
  secret_key_base: cd339092d839cbe1c6677965d4581f009544f4cc19e05bc86a78487835a5974e67ba770fa01fe607a8fc0193ce445b9a35bf5982284c65876d3e61ef37f3a2ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
